/**
 * Merge pronunciation JSON (phonetic from LLM) with ipa-dict upgrades (authoritative IPA)
 * into a single migration SQL file.
 *
 * Usage: bun scripts/hint-pipeline/merge-pronunciation-low-levels.ts
 */

const DATA_DIR = new URL('./data/', import.meta.url).pathname;

interface PronunciationWord {
  word: string;
  ipa: string;
  phonetic: string;
}

interface PronunciationData {
  words: PronunciationWord[];
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

async function loadIpaDict(): Promise<Map<string, string>> {
  const path = `${DATA_DIR}ipa-dict-en_US.txt`;
  const content = await Bun.file(path).text();
  const dict = new Map<string, string>();

  for (const line of content.split('\n')) {
    if (!line.trim()) continue;
    const tab = line.indexOf('\t');
    if (tab === -1) continue;
    const word = line.slice(0, tab).toLowerCase();
    const ipa = line.slice(tab + 1).trim();
    dict.set(word, ipa);
  }

  return dict;
}

async function main() {
  const date = today();
  const jsonPath = `${DATA_DIR}pronunciation-low-levels-${date}.json`;

  const data = (await Bun.file(jsonPath).json()) as PronunciationData;
  const ipaDict = await loadIpaDict();

  const lines: string[] = [
    `-- Populate IPA and phonetic respelling for level 1-4 words`,
    `-- ${data.words.length} words with pronunciation data`,
    `-- IPA from ipa-dict (CMUdict-based, MIT licensed) where available`,
    `-- Phonetic respelling generated by Claude Haiku 4.5`,
    `-- Generated on ${date}`,
    ``,
  ];

  let dictCount = 0;
  let llmCount = 0;

  const sorted = [...data.words].sort((a, b) =>
    a.word.localeCompare(b.word)
  );

  for (const entry of sorted) {
    const word = escapeSQL(entry.word);
    const phonetic = escapeSQL(entry.phonetic);

    // Prefer ipa-dict, fall back to Wiktionary/LLM
    const dictIpa = ipaDict.get(entry.word.toLowerCase());
    let ipa: string;
    if (dictIpa) {
      ipa = escapeSQL(dictIpa);
      dictCount++;
    } else {
      ipa = escapeSQL(entry.ipa);
      llmCount++;
    }

    lines.push(
      `UPDATE spelling_word_bank SET ipa = '${ipa}', phonetic = '${phonetic}' WHERE word = '${word}';`
    );
  }

  lines.push('');

  const sqlPath = `${DATA_DIR}pronunciation-low-levels-merged-${date}.sql`;
  await Bun.write(sqlPath, lines.join('\n'));

  console.log(`Merged migration: ${sqlPath}`);
  console.log(`Total: ${sorted.length} words`);
  console.log(`IPA from ipa-dict: ${dictCount}`);
  console.log(`IPA from Wiktionary/LLM: ${llmCount}`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
