import Link from 'next/link';
import { PATTERN_TEMPLATES } from '@/lib/spelling/lessons/patterns';

export const metadata = {
  title: 'Spelling Patterns — SpellBetterNow',
  description: 'The full curated library of spelling patterns used in SpellBetterNow tips.',
};

export default function PatternsPage() {
  const patterns = Object.values(PATTERN_TEMPLATES);

  return (
    <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)]">
      <div className="max-w-2xl mx-auto px-4 py-12">
        <Link
          href="/landing"
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          &larr; Back
        </Link>

        <h1 className="text-2xl font-bold mt-6 mb-2">Spelling Patterns</h1>
        <p className="text-sm text-muted-foreground mb-8">
          After each 5-word set, SpellBetterNow shows a spelling tip matched to your
          learner&apos;s missed word. These tips come from the curated library below — they&apos;re
          not generated by AI. A pattern detector checks the missed word and picks the
          most relevant tip.
        </p>

        <p className="text-xs text-muted-foreground mb-8">
          {patterns.length} patterns in the library
        </p>

        <div className="space-y-6">
          {patterns.map((pattern) => (
            <div
              key={pattern.name}
              className="border border-border rounded-lg p-4 space-y-3"
            >
              <h2 className="font-semibold text-sm">
                {pattern.name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}
              </h2>
              <p className="text-sm">{pattern.explanation}</p>
              {pattern.contrast.length > 0 && (
                <div className="text-sm text-muted-foreground space-y-0.5">
                  {pattern.contrast.map((line, i) => (
                    <div key={`${pattern.name}-${i}`} className="font-mono text-xs">
                      {line}
                    </div>
                  ))}
                </div>
              )}
              {pattern.question && (
                <div className="text-sm border-t border-border pt-2 mt-2">
                  <p className="text-muted-foreground italic">{pattern.question}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    Answer: {pattern.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="mt-12 text-xs text-muted-foreground border-t border-border pt-6 space-y-2">
          <p>
            This library is open and visible so parents and teachers can see exactly what
            tips their learners receive. If a tip didn&apos;t make sense during a session, use
            the feedback button on the break screen to let us know.
          </p>
          <p>
            Patterns are matched by checking the correct spelling of the missed word. The
            first matching pattern wins — so &quot;knight&quot; matches &quot;silent letters&quot; (the kn-)
            rather than &quot;-ight words.&quot;
          </p>
        </div>
      </div>
    </main>
  );
}
