-- Upgrade IPA from LLM-generated to ipa-dict (CMUdict-based, MIT licensed)
-- 462 words upgraded with authoritative General American IPA
-- Source: https://github.com/open-dict-data/ipa-dict (en_US)
-- 64 words remain with LLM-generated IPA (rare/scientific terms)

UPDATE spelling_word_bank SET ipa = '/ækˈsɛɫɝˌeɪt/' WHERE word = 'accelerate';
UPDATE spelling_word_bank SET ipa = '/ækˈsɛɫɝˌeɪtɪŋ/' WHERE word = 'accelerating';
UPDATE spelling_word_bank SET ipa = '/ˌækˌsɛɫɝˈeɪʃən/' WHERE word = 'acceleration';
UPDATE spelling_word_bank SET ipa = '/ˌæksɛsəˈbɪɫɪti/' WHERE word = 'accessibility';
UPDATE spelling_word_bank SET ipa = '/ækˈsɛsəbəɫ/' WHERE word = 'accessible';
UPDATE spelling_word_bank SET ipa = '/əˈkəmpənid/' WHERE word = 'accompanied';
UPDATE spelling_word_bank SET ipa = '/əˈkəmpəni/' WHERE word = 'accompany';
UPDATE spelling_word_bank SET ipa = '/əkˈjumjəˌɫeɪt/' WHERE word = 'accumulate';
UPDATE spelling_word_bank SET ipa = '/əkˌjumjəˈɫeɪʃən/' WHERE word = 'accumulation';
UPDATE spelling_word_bank SET ipa = '/əˈtʃivmənt/' WHERE word = 'achievement';
UPDATE spelling_word_bank SET ipa = '/ækˈnɑɫɪdʒ/' WHERE word = 'acknowledge';
UPDATE spelling_word_bank SET ipa = '/ædˌmɪnɪˈstɹeɪʃən/' WHERE word = 'administration';
UPDATE spelling_word_bank SET ipa = '/ˌædəˈɫɛsənt/, /ˌædoʊˈɫɛsənt/' WHERE word = 'adolescent';
UPDATE spelling_word_bank SET ipa = '/ˈæfɫuəns/' WHERE word = 'affluence';
UPDATE spelling_word_bank SET ipa = '/ˈæɡɹəɡeɪt/, /ˈæɡɹəɡət/, /ˈæɡɹəɡɪt/' WHERE word = 'aggregate';
UPDATE spelling_word_bank SET ipa = '/əˈɡɹɛʃən/' WHERE word = 'aggression';
UPDATE spelling_word_bank SET ipa = '/ˈæɫəˌkeɪt/' WHERE word = 'allocate';
UPDATE spelling_word_bank SET ipa = '/ˈɔɫtɝˌneɪtɪŋ/' WHERE word = 'alternating';
UPDATE spelling_word_bank SET ipa = '/ɔɫˈtɝnətɪv/' WHERE word = 'alternative';
UPDATE spelling_word_bank SET ipa = '/ˌɔɫˈðoʊ/' WHERE word = 'although';
UPDATE spelling_word_bank SET ipa = '/əˈmiɫjɝˌeɪt/' WHERE word = 'ameliorate';
UPDATE spelling_word_bank SET ipa = '/əˌnækɹəˈnɪstɪk/' WHERE word = 'anachronistic';
UPDATE spelling_word_bank SET ipa = '/ˈænəˌɫaɪz/' WHERE word = 'analyze';
UPDATE spelling_word_bank SET ipa = '/əˈnaʊnsmənt/, /əˈnaʊnsmɛnt/' WHERE word = 'announcement';
UPDATE spelling_word_bank SET ipa = '/ˌæntəˈθɛtɪkəɫ/' WHERE word = 'antithetical';
UPDATE spelling_word_bank SET ipa = '/əˈpɑstɹəˌfiz/' WHERE word = 'apostrophes';
UPDATE spelling_word_bank SET ipa = '/ˌæpɝˈætəs/' WHERE word = 'apparatus';
UPDATE spelling_word_bank SET ipa = '/əˈpizmənt/' WHERE word = 'appeasement';
UPDATE spelling_word_bank SET ipa = '/əˌpɹiʃiˈeɪʃən/' WHERE word = 'appreciation';
UPDATE spelling_word_bank SET ipa = '/əˈpɹoʊpɹiˌeɪt/, /əˈpɹoʊpɹiət/' WHERE word = 'appropriate';
UPDATE spelling_word_bank SET ipa = '/əˈpɹoʊpɹiɪtɫi/' WHERE word = 'appropriately';
UPDATE spelling_word_bank SET ipa = '/əˈpɹɑksəˌmeɪt/, /əˈpɹɑksəmət/' WHERE word = 'approximate';
UPDATE spelling_word_bank SET ipa = '/əˈpɹɑksəmətɫi/' WHERE word = 'approximately';
UPDATE spelling_word_bank SET ipa = '/əˌpɹɑksəˈmeɪʃən/' WHERE word = 'approximation';
UPDATE spelling_word_bank SET ipa = '/ɝˈeɪndʒmənt/' WHERE word = 'arrangement';
UPDATE spelling_word_bank SET ipa = '/əˌsæsəˈneɪʃən/' WHERE word = 'assassination';
UPDATE spelling_word_bank SET ipa = '/əˈsɛs/' WHERE word = 'assess';
UPDATE spelling_word_bank SET ipa = '/əˌsɪməˈɫeɪʃən/' WHERE word = 'assimilation';
UPDATE spelling_word_bank SET ipa = '/əˈsoʊʃəˌtɪv/' WHERE word = 'associative';
UPDATE spelling_word_bank SET ipa = '/ˈætməsˌfɪɹ/' WHERE word = 'atmosphere';
UPDATE spelling_word_bank SET ipa = '/ˌɔtəˈmætɪkɫi/, /ˌɔtoʊˈmætɪkɫi/' WHERE word = 'automatically';
UPDATE spelling_word_bank SET ipa = '/əˈwɛɹnəs/' WHERE word = 'awareness';
UPDATE spelling_word_bank SET ipa = '/ˌbuˌɡeɪnˈvɪɫiə/' WHERE word = 'bougainvillea';
UPDATE spelling_word_bank SET ipa = '/ˈbʊɹʒwɑ/, /bʊɹʒˈwɑ/' WHERE word = 'bourgeois';
UPDATE spelling_word_bank SET ipa = '/ˌbʊɹʒˌwɑˈzi/' WHERE word = 'bourgeoisie';
UPDATE spelling_word_bank SET ipa = '/ˈbɹeɪkˌθɹu/' WHERE word = 'breakthrough';
UPDATE spelling_word_bank SET ipa = '/bjʊˈɹɑkɹəsi/' WHERE word = 'bureaucracy';
UPDATE spelling_word_bank SET ipa = '/kæˈkɑfəni/' WHERE word = 'cacophony';
UPDATE spelling_word_bank SET ipa = '/ˌkæpɪtəɫɪˈzeɪʃən/' WHERE word = 'capitalization';
UPDATE spelling_word_bank SET ipa = '/kəˈpɹɪʃəs/' WHERE word = 'capricious';
UPDATE spelling_word_bank SET ipa = '/ˌkɑɹboʊˈhaɪˌdɹeɪt/, /ˌkɑɹboʊˈhaɪdɹət/' WHERE word = 'carbohydrate';
UPDATE spelling_word_bank SET ipa = '/ˈkætəˌkɫɪsəm/' WHERE word = 'cataclysm';
UPDATE spelling_word_bank SET ipa = '/ˈkætəɫɔɡ/' WHERE word = 'catalog';
UPDATE spelling_word_bank SET ipa = '/ˈtʃæɫəndʒɪŋ/' WHERE word = 'challenging';
UPDATE spelling_word_bank SET ipa = '/ˈkɛməkɫi/' WHERE word = 'chemically';
UPDATE spelling_word_bank SET ipa = '/ʃəˈmiz/' WHERE word = 'chemise';
UPDATE spelling_word_bank SET ipa = '/ˈkɫɔɹəfɪɫ/' WHERE word = 'chlorophyll';
UPDATE spelling_word_bank SET ipa = '/kəˈɫɛstɝˌɔɫ/, /kəˈɫɛstɝəɫ/' WHERE word = 'cholesterol';
UPDATE spelling_word_bank SET ipa = '/kɹoʊməˈtɑɡɹəfi/' WHERE word = 'chromatography';
UPDATE spelling_word_bank SET ipa = '/kɹɪˈsænθəməm/' WHERE word = 'chrysanthemum';
UPDATE spelling_word_bank SET ipa = '/ˌsɝˈkəmfɹəns/' WHERE word = 'circumference';
UPDATE spelling_word_bank SET ipa = '/ˈsɝkəmˌstæns/' WHERE word = 'circumstance';
UPDATE spelling_word_bank SET ipa = '/ˈsɪtɪzənˌʃɪp/' WHERE word = 'citizenship';
UPDATE spelling_word_bank SET ipa = '/ˌkɫæsəfəˈkeɪʃən/' WHERE word = 'classification';
UPDATE spelling_word_bank SET ipa = '/ˌkoʊəˈfɪʃənt/' WHERE word = 'coefficient';
UPDATE spelling_word_bank SET ipa = '/kəˌɫæbɝˈeɪʃən/' WHERE word = 'collaboration';
UPDATE spelling_word_bank SET ipa = '/kəˈɫæps/' WHERE word = 'collapse';
UPDATE spelling_word_bank SET ipa = '/kəˈɫoʊkwiəɫ/' WHERE word = 'colloquial';
UPDATE spelling_word_bank SET ipa = '/kəˈmɪʃənɝ/' WHERE word = 'commissioner';
UPDATE spelling_word_bank SET ipa = '/kəˈmɪʃənɝz/' WHERE word = 'commissioners';
UPDATE spelling_word_bank SET ipa = '/kəˈmɑdəti/' WHERE word = 'commodity';
UPDATE spelling_word_bank SET ipa = '/kəmˈjunəkəbəɫ/' WHERE word = 'communicable';
UPDATE spelling_word_bank SET ipa = '/kəmˈjunəˌkeɪt/' WHERE word = 'communicate';
UPDATE spelling_word_bank SET ipa = '/kəmˈjunəˌkeɪtɪŋ/' WHERE word = 'communicating';
UPDATE spelling_word_bank SET ipa = '/kəmˌjunəˈkeɪʃən/' WHERE word = 'communication';
UPDATE spelling_word_bank SET ipa = '/kəmˈjunətiz/, /kəmˈjunɪtiz/' WHERE word = 'communities';
UPDATE spelling_word_bank SET ipa = '/kəmˈpɛtɪtɪvnɪs/' WHERE word = 'competitiveness';
UPDATE spelling_word_bank SET ipa = '/ˈkɑmpɫəmənt/' WHERE word = 'complement';
UPDATE spelling_word_bank SET ipa = '/ˌkɑmpɫəˈmɛntɹi/, /ˌkɑmpɫəˈmɛntʃi/' WHERE word = 'complementary';
UPDATE spelling_word_bank SET ipa = '/ˈkɑnsənˌtɹeɪtɪd/' WHERE word = 'concentrated';
UPDATE spelling_word_bank SET ipa = '/ˌkɑnsənˈtɹeɪʃən/' WHERE word = 'concentration';
UPDATE spelling_word_bank SET ipa = '/kənˌfɪɡjɝˈeɪʃən/' WHERE word = 'configuration';
UPDATE spelling_word_bank SET ipa = '/ˈkɑŋɡɹəs/' WHERE word = 'congress';
UPDATE spelling_word_bank SET ipa = '/kənˈɡɹɛʃənəɫ/' WHERE word = 'congressional';
UPDATE spelling_word_bank SET ipa = '/ˈkɑnʃəns/' WHERE word = 'conscience';
UPDATE spelling_word_bank SET ipa = '/ˌkɑnʃiˈɛnʃəs/' WHERE word = 'conscientious';
UPDATE spelling_word_bank SET ipa = '/ˈkɑnʃəs/' WHERE word = 'conscious';
UPDATE spelling_word_bank SET ipa = '/ˈkɑnsəkwənt/' WHERE word = 'consequent';
UPDATE spelling_word_bank SET ipa = '/ˈkɑnsəˌkwɛntɫi/, /ˈkɑnsəkwəntɫi/' WHERE word = 'consequently';
UPDATE spelling_word_bank SET ipa = '/ˌkɑnsɝˈveɪʃən/' WHERE word = 'conservation';
UPDATE spelling_word_bank SET ipa = '/ˌkɑnstəˈtuʃənəɫ/' WHERE word = 'constitutional';
UPDATE spelling_word_bank SET ipa = '/ˌkɑntəˈnɛnəɫ/, /ˌkɑntəˈnɛntəɫ/' WHERE word = 'continental';
UPDATE spelling_word_bank SET ipa = '/kənˈtɹæstɪŋ/' WHERE word = 'contrasting';
UPDATE spelling_word_bank SET ipa = '/ˈkɑntɹəˌvɝsi/' WHERE word = 'controversy';
UPDATE spelling_word_bank SET ipa = '/koʊˈɔɹdəˌneɪt/, /koʊˈɔɹdənət/' WHERE word = 'coordinate';
UPDATE spelling_word_bank SET ipa = '/koʊˌɔɹdəˈneɪʃən/' WHERE word = 'coordination';
UPDATE spelling_word_bank SET ipa = '/ˌkɔɹpɝˈeɪʃən/' WHERE word = 'corporation';
UPDATE spelling_word_bank SET ipa = '/ˌkɔɹəˈspɑnd/' WHERE word = 'correspond';
UPDATE spelling_word_bank SET ipa = '/ˌkɔɹəˈspɑndəns/' WHERE word = 'correspondence';
UPDATE spelling_word_bank SET ipa = '/ˌkɔɹəˈspɑndɪŋ/' WHERE word = 'corresponding';
UPDATE spelling_word_bank SET ipa = '/kɹɪˈʃɛndoʊ/' WHERE word = 'crescendo';
UPDATE spelling_word_bank SET ipa = '/kɝˈɪkjəɫəm/' WHERE word = 'curriculum';
UPDATE spelling_word_bank SET ipa = '/ˈdɛsəməɫ/' WHERE word = 'decimal';
UPDATE spelling_word_bank SET ipa = '/dɪˈɫɪniˌeɪt/' WHERE word = 'delineate';
UPDATE spelling_word_bank SET ipa = '/ˈdɛmənˌstɹeɪt/' WHERE word = 'demonstrate';
UPDATE spelling_word_bank SET ipa = '/dɪˈnɑməˌneɪtɝ/' WHERE word = 'denominator';
UPDATE spelling_word_bank SET ipa = '/ˈdaɪəˌɫɔɡ/' WHERE word = 'dialogue';
UPDATE spelling_word_bank SET ipa = '/ˌdɪfɝˈɛnʃiˌeɪt/, /ˌdɪfɝˈɛntʃiˌeɪt/' WHERE word = 'differentiate';
UPDATE spelling_word_bank SET ipa = '/ˌdɪfɝˌɛntʃiˈeɪʃən/, /dɪfɝˌɛnʃiˈeɪʃən/' WHERE word = 'differentiation';
UPDATE spelling_word_bank SET ipa = '/ˈdɪɫədʒəns/, /ˈdɪɫɪdʒəns/' WHERE word = 'diligence';
UPDATE spelling_word_bank SET ipa = '/dɪˈmɛnʃənəɫ/' WHERE word = 'dimensional';
UPDATE spelling_word_bank SET ipa = '/dɪfˈθɪɹiɑ/' WHERE word = 'diphtheria';
UPDATE spelling_word_bank SET ipa = '/dɪsˌkɹɪməˈneɪʃən/' WHERE word = 'discrimination';
UPDATE spelling_word_bank SET ipa = '/dɪsˈpɫeɪsmənt/' WHERE word = 'displacement';
UPDATE spelling_word_bank SET ipa = '/dɪˈspoʊzəbəɫ/' WHERE word = 'disposable';
UPDATE spelling_word_bank SET ipa = '/dɪˈzɑɫv/' WHERE word = 'dissolve';
UPDATE spelling_word_bank SET ipa = '/dəˈmɛstɪkɫi/' WHERE word = 'domestically';
UPDATE spelling_word_bank SET ipa = '/ˈdɑməˌneɪt/' WHERE word = 'dominate';
UPDATE spelling_word_bank SET ipa = '/dɹəˈmætɪkəɫi/, /dɹəˈmætɪkɫi/' WHERE word = 'dramatically';
UPDATE spelling_word_bank SET ipa = '/ˌɛksənˈtɹɪsəti/' WHERE word = 'eccentricity';
UPDATE spelling_word_bank SET ipa = '/ˌɛkəˈnɑmɪkɫi/, /ˌikəˈnɑmɪkɫi/' WHERE word = 'economically';
UPDATE spelling_word_bank SET ipa = '/ˌɛfɝˈvɛsənt/' WHERE word = 'effervescent';
UPDATE spelling_word_bank SET ipa = '/ɪˈfɪʃəntɫi/' WHERE word = 'efficiently';
UPDATE spelling_word_bank SET ipa = '/ɪˈɫɛktɹɪkəɫi/, /ɪˈɫɛktɹɪkɫi/' WHERE word = 'electrically';
UPDATE spelling_word_bank SET ipa = '/ˌɪˌɫɛktɹoʊmæɡˈnɛtɪk/' WHERE word = 'electromagnetic';
UPDATE spelling_word_bank SET ipa = '/ˌɛɫəˈmɔsəˌnɛɹi/' WHERE word = 'eleemosynary';
UPDATE spelling_word_bank SET ipa = '/ɪˌɫɪməˈneɪʃən/' WHERE word = 'elimination';
UPDATE spelling_word_bank SET ipa = '/ɪmˈbɛɹəs/' WHERE word = 'embarrass';
UPDATE spelling_word_bank SET ipa = '/ɪmˈbɛɹəsmənt/' WHERE word = 'embarrassment';
UPDATE spelling_word_bank SET ipa = '/ˈimɝdʒəns/, /ɪˈmɝdʒəns/' WHERE word = 'emergence';
UPDATE spelling_word_bank SET ipa = '/ˌɛnɝˈdʒɛtɪkɫi/' WHERE word = 'energetically';
UPDATE spelling_word_bank SET ipa = '/ɛnˈhæns/' WHERE word = 'enhance';
UPDATE spelling_word_bank SET ipa = '/iˈnəf/, /ɪˈnəf/' WHERE word = 'enough';
UPDATE spelling_word_bank SET ipa = '/ˌɑntɹəpɹəˈnɝ/, /ˌɑntɹəpɹəˈnʊɹ/' WHERE word = 'entrepreneur';
UPDATE spelling_word_bank SET ipa = '/ɪnˈvaɪɹənmənt/' WHERE word = 'environment';
UPDATE spelling_word_bank SET ipa = '/ɪnˌvaɪɹənˈmɛnəɫ/, /ɪnˌvaɪɹənˈmɛntəɫ/' WHERE word = 'environmental';
UPDATE spelling_word_bank SET ipa = '/ɪnˌvaɪɹənˈmɛnəɫi/, /ɪnˌvaɪɹənˈmɛntəɫi/' WHERE word = 'environmentally';
UPDATE spelling_word_bank SET ipa = '/ˈɛpəˌɫɔɡ/' WHERE word = 'epilogue';
UPDATE spelling_word_bank SET ipa = '/ˌikwəˈɫɪbɹiəm/' WHERE word = 'equilibrium';
UPDATE spelling_word_bank SET ipa = '/ɪˈkwɪvəɫənt/' WHERE word = 'equivalent';
UPDATE spelling_word_bank SET ipa = '/ˈɛɹəˌdaɪt/' WHERE word = 'erudite';
UPDATE spelling_word_bank SET ipa = '/ɪˈstæbɫɪʃmənt/' WHERE word = 'establishment';
UPDATE spelling_word_bank SET ipa = '/əˈvɛntʃuəɫ/, /iˈvɛntʃuəɫ/' WHERE word = 'eventual';
UPDATE spelling_word_bank SET ipa = '/ˈɛvədənt/' WHERE word = 'evident';
UPDATE spelling_word_bank SET ipa = '/ˈju/' WHERE word = 'ewe';
UPDATE spelling_word_bank SET ipa = '/ɪɡˈzæsɝˌbeɪt/' WHERE word = 'exacerbate';
UPDATE spelling_word_bank SET ipa = '/ˌɛkskɫəˈmeɪʃən/' WHERE word = 'exclamation';
UPDATE spelling_word_bank SET ipa = '/ˌɛkspoʊˈnɛnʃəɫ/' WHERE word = 'exponential';
UPDATE spelling_word_bank SET ipa = '/ˈɛkspɔɹt/' WHERE word = 'export';
UPDATE spelling_word_bank SET ipa = '/fəˈsɪɫəˌteɪt/' WHERE word = 'facilitate';
UPDATE spelling_word_bank SET ipa = '/fɪˈɫɪsətəs/' WHERE word = 'felicitous';
UPDATE spelling_word_bank SET ipa = '/ˈfɝvəd/' WHERE word = 'fervid';
UPDATE spelling_word_bank SET ipa = '/ˌfɫɛksəˈbɪɫəti/' WHERE word = 'flexibility';
UPDATE spelling_word_bank SET ipa = '/ˈfɑsəɫ/' WHERE word = 'fossil';
UPDATE spelling_word_bank SET ipa = '/ˈfɹækʃənəɫ/' WHERE word = 'fractional';
UPDATE spelling_word_bank SET ipa = '/ˌfəndəˈmɛnəɫ/, /ˌfəndəˈmɛntəɫ/' WHERE word = 'fundamental';
UPDATE spelling_word_bank SET ipa = '/ˈɡɛɹəɫəs/' WHERE word = 'garrulous';
UPDATE spelling_word_bank SET ipa = '/dʒəˈnɛtɪkɫi/' WHERE word = 'genetically';
UPDATE spelling_word_bank SET ipa = '/ˌdʒiəˈɡɹæfɪkəɫ/' WHERE word = 'geographical';
UPDATE spelling_word_bank SET ipa = '/ˈɡɹeɪsfəɫ/' WHERE word = 'graceful';
UPDATE spelling_word_bank SET ipa = '/ɡɹəˈmætəkəɫ/, /ɡɹəˈmætɪkəɫ/' WHERE word = 'grammatical';
UPDATE spelling_word_bank SET ipa = '/ˈɡɹænt/' WHERE word = 'grant';
UPDATE spelling_word_bank SET ipa = '/ˈɡɹæfɪkɫi/' WHERE word = 'graphically';
UPDATE spelling_word_bank SET ipa = '/ˈɡɹæsˌhɑpɝ/' WHERE word = 'grasshopper';
UPDATE spelling_word_bank SET ipa = '/ˌɡɹævɪˈteɪʃənəɫ/' WHERE word = 'gravitational';
UPDATE spelling_word_bank SET ipa = '/ɡɹəˈɡɛɹiəs/' WHERE word = 'gregarious';
UPDATE spelling_word_bank SET ipa = '/ˈɡɹaʊndˌwɑtɝ/, /ˈɡɹaʊndˌwɔtɝ/' WHERE word = 'groundwater';
UPDATE spelling_word_bank SET ipa = '/ɡuˌbɝnəˈtɔˌɹiəɫ/' WHERE word = 'gubernatorial';
UPDATE spelling_word_bank SET ipa = '/ɡɝˈɪɫə/' WHERE word = 'guerrilla';
UPDATE spelling_word_bank SET ipa = '/hɝˈæs/' WHERE word = 'harass';
UPDATE spelling_word_bank SET ipa = '/hɝˈæsmənt/' WHERE word = 'harassment';
UPDATE spelling_word_bank SET ipa = '/ˈhaɪt/' WHERE word = 'height';
UPDATE spelling_word_bank SET ipa = '/ˈhɛmɪsˌfɪɹ/' WHERE word = 'hemisphere';
UPDATE spelling_word_bank SET ipa = '/ˈhɛmɝɪdʒ/, /ˈhɛmɹədʒ/' WHERE word = 'hemorrhage';
UPDATE spelling_word_bank SET ipa = '/ˌhɛtɝəˈzaɪɡəs/' WHERE word = 'heterozygous';
UPDATE spelling_word_bank SET ipa = '/ˈhaɪˌɫaɪt/' WHERE word = 'highlight';
UPDATE spelling_word_bank SET ipa = '/ˈhaɪˌɫaɪtɪd/' WHERE word = 'highlighted';
UPDATE spelling_word_bank SET ipa = '/ˈhaɪˌɫaɪtɪŋ/' WHERE word = 'highlighting';
UPDATE spelling_word_bank SET ipa = '/ˌhoʊməˈdʒiniəs/' WHERE word = 'homogeneous';
UPDATE spelling_word_bank SET ipa = '/ˌhɔɹəˈzɑntəɫ/' WHERE word = 'horizontal';
UPDATE spelling_word_bank SET ipa = '/ˌhɔɹɪˈzɑntəɫi/, /hɔɹɪˈzɔnəɫi/' WHERE word = 'horizontally';
UPDATE spelling_word_bank SET ipa = '/haɪˈpɑθəsəs/' WHERE word = 'hypothesis';
UPDATE spelling_word_bank SET ipa = '/aɪˌdɛntəfəˈkeɪʃən/' WHERE word = 'identification';
UPDATE spelling_word_bank SET ipa = '/ˌɪdioʊˈsɪnkɹəˌsi/' WHERE word = 'idiosyncrasy';
UPDATE spelling_word_bank SET ipa = '/ˈɪɫəˌstɹeɪt/' WHERE word = 'illustrate';
UPDATE spelling_word_bank SET ipa = '/ˌɪɫəˈstɹeɪʃən/' WHERE word = 'illustration';
UPDATE spelling_word_bank SET ipa = '/ˌɪməˈɡɹeɪʃən/' WHERE word = 'immigration';
UPDATE spelling_word_bank SET ipa = '/ˌɪˈmɪsəbəɫ/' WHERE word = 'immiscible';
UPDATE spelling_word_bank SET ipa = '/ˌɪmjunoʊˌdɪˈfɪʃənsi/' WHERE word = 'immunodeficiency';
UPDATE spelling_word_bank SET ipa = '/ˈɪmˌpɹɛs/, /ˌɪmˈpɹɛs/' WHERE word = 'impress';
UPDATE spelling_word_bank SET ipa = '/ˈɪnsədəns/, /ˈɪnsɪdəns/' WHERE word = 'incidence';
UPDATE spelling_word_bank SET ipa = '/ˌɪnkəmˈpætəbəɫ/' WHERE word = 'incompatible';
UPDATE spelling_word_bank SET ipa = '/ˌɪnkənˈsɪstənt/' WHERE word = 'inconsistent';
UPDATE spelling_word_bank SET ipa = '/ˌɪndɪˈfætɪɡəbəɫ/' WHERE word = 'indefatigable';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈdɪdʒənəs/' WHERE word = 'indigenous';
UPDATE spelling_word_bank SET ipa = '/ˌɪndəˈvɪdʒəwəɫ/' WHERE word = 'individual';
UPDATE spelling_word_bank SET ipa = '/ˌɪˈnɛfəbəɫ/' WHERE word = 'ineffable';
UPDATE spelling_word_bank SET ipa = '/ˈɪniˈkwɑɫɪtiz/, /ˌɪnəˈkwɑɫɪtiz/, /ˌɪnɪˈkwɑɫɪtiz/' WHERE word = 'inequalities';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈfɛkʃəs/' WHERE word = 'infectious';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈfɫeɪʃəˌnɛɹi/' WHERE word = 'inflationary';
UPDATE spelling_word_bank SET ipa = '/ˌɪˈnɪʃəɫ/' WHERE word = 'initial';
UPDATE spelling_word_bank SET ipa = '/ˌɪnəˈveɪʃən/, /ˌɪnoʊˈveɪʃən/' WHERE word = 'innovation';
UPDATE spelling_word_bank SET ipa = '/ˌɪnsˈkɹutəbəɫ/' WHERE word = 'inscrutable';
UPDATE spelling_word_bank SET ipa = '/ˌɪnsɪkˈjʊɹɪti/' WHERE word = 'insecurity';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈsusjənt/' WHERE word = 'insouciant';
UPDATE spelling_word_bank SET ipa = '/ˈɪnstəˌtut/' WHERE word = 'institute';
UPDATE spelling_word_bank SET ipa = '/ˌɪnstɪˈtuʃən/' WHERE word = 'institution';
UPDATE spelling_word_bank SET ipa = '/ˌɪnəˈɡɹeɪʃən/, /ˌɪntəˈɡɹeɪʃən/' WHERE word = 'integration';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈtɛɫədʒəns/' WHERE word = 'intelligence';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈtɛɫədʒənt/' WHERE word = 'intelligent';
UPDATE spelling_word_bank SET ipa = '/ˌɪntɝˈsɛɫjəɫɝ/' WHERE word = 'intercellular';
UPDATE spelling_word_bank SET ipa = '/ˌɪnɝˈmidiɪt/, /ˌɪntɝˈmidiɪt/' WHERE word = 'intermediate';
UPDATE spelling_word_bank SET ipa = '/ˌɪntɝɹɪˈɫeɪt/' WHERE word = 'interrelate';
UPDATE spelling_word_bank SET ipa = '/ˈɪntɝvəɫ/' WHERE word = 'interval';
UPDATE spelling_word_bank SET ipa = '/ˌɪntɝˈvɛnʃən/' WHERE word = 'intervention';
UPDATE spelling_word_bank SET ipa = '/ˈɪntɝvˌju/' WHERE word = 'interview';
UPDATE spelling_word_bank SET ipa = '/ˈɪntɹiɡ/, /ˌɪnˈtɹiɡ/' WHERE word = 'intrigue';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈvɛstəˌɡeɪt/' WHERE word = 'investigate';
UPDATE spelling_word_bank SET ipa = '/ˌɪnˈvɑɫvmənt/' WHERE word = 'involvement';
UPDATE spelling_word_bank SET ipa = '/ˌaɪsəˈɫeɪʃəˌnɪzəm/' WHERE word = 'isolationism';
UPDATE spelling_word_bank SET ipa = '/ˈɪʃu/' WHERE word = 'issue';
UPDATE spelling_word_bank SET ipa = '/aɪˈtɪnɝˌɛɹi/' WHERE word = 'itinerary';
UPDATE spelling_word_bank SET ipa = '/ˈdʒədʒmənt/' WHERE word = 'judgement';
UPDATE spelling_word_bank SET ipa = '/ˈdʒədʒmənt/' WHERE word = 'judgment';
UPDATE spelling_word_bank SET ipa = '/ˌdʒəkstəˈpoʊz/' WHERE word = 'juxtapose';
UPDATE spelling_word_bank SET ipa = '/ˌdʒəkstəpəˈzɪʃən/' WHERE word = 'juxtaposition';
UPDATE spelling_word_bank SET ipa = '/kəˈɫaɪdəˌskoʊp/' WHERE word = 'kaleidoscope';
UPDATE spelling_word_bank SET ipa = '/ˈnɑɫədʒ/, /ˈnɑɫɪdʒ/' WHERE word = 'knowledge';
UPDATE spelling_word_bank SET ipa = '/ˈɫæbɹəˌtɔɹi/' WHERE word = 'laboratory';
UPDATE spelling_word_bank SET ipa = '/ˌɫæbɝˈɪnˌθin/' WHERE word = 'labyrinthine';
UPDATE spelling_word_bank SET ipa = '/ˌɫɛdʒəˈsɫeɪʃən/' WHERE word = 'legislation';
UPDATE spelling_word_bank SET ipa = '/ˈɫɪˌbɝˌeɪt/' WHERE word = 'liberate';
UPDATE spelling_word_bank SET ipa = '/ɫuˈtɛnənt/' WHERE word = 'lieutenant';
UPDATE spelling_word_bank SET ipa = '/ɫoʊˈkweɪʃəs/' WHERE word = 'loquacious';
UPDATE spelling_word_bank SET ipa = '/mæɡˈnænəməs/' WHERE word = 'magnanimous';
UPDATE spelling_word_bank SET ipa = '/məˈnɪpjəˌɫeɪt/' WHERE word = 'manipulate';
UPDATE spelling_word_bank SET ipa = '/ˌmæθəˈmætɪkəɫ/' WHERE word = 'mathematical';
UPDATE spelling_word_bank SET ipa = '/ˈmæksəməm/' WHERE word = 'maximum';
UPDATE spelling_word_bank SET ipa = '/ˌmɛdətɝˈeɪniən/' WHERE word = 'mediterranean';
UPDATE spelling_word_bank SET ipa = '/ˌmɛtəˈmɔɹfəsəs/' WHERE word = 'metamorphosis';
UPDATE spelling_word_bank SET ipa = '/məˈɫɛniə/' WHERE word = 'millennia';
UPDATE spelling_word_bank SET ipa = '/məˈɫɛniəm/' WHERE word = 'millennium';
UPDATE spelling_word_bank SET ipa = '/ˈmɪstʃəvəs/' WHERE word = 'mischievous';
UPDATE spelling_word_bank SET ipa = '/ˈmɪskɹiənt/' WHERE word = 'miscreant';
UPDATE spelling_word_bank SET ipa = '/ˈmɑnəˌɫɔɡ/' WHERE word = 'monologue';
UPDATE spelling_word_bank SET ipa = '/ˈnæɹətɪv/, /ˈnɛɹətɪv/' WHERE word = 'narrative';
UPDATE spelling_word_bank SET ipa = '/ˈnɛɡətɪvɫi/' WHERE word = 'negatively';
UPDATE spelling_word_bank SET ipa = '/ˈneɪbɝ/' WHERE word = 'neighbor';
UPDATE spelling_word_bank SET ipa = '/ˈneɪbɝˌhʊd/' WHERE word = 'neighbourhood';
UPDATE spelling_word_bank SET ipa = '/ˈnutɹəɫ/' WHERE word = 'neutral';
UPDATE spelling_word_bank SET ipa = '/nuˈtɹæɫəti/' WHERE word = 'neutrality';
UPDATE spelling_word_bank SET ipa = '/ˌnɛvɝðəˈɫɛs/' WHERE word = 'nevertheless';
UPDATE spelling_word_bank SET ipa = '/ˌnɑnʃəˈɫɑnt/' WHERE word = 'nonchalant';
UPDATE spelling_word_bank SET ipa = '/ˈnutɹiənt/' WHERE word = 'nutrient';
UPDATE spelling_word_bank SET ipa = '/ˈɑbfəˌskeɪt/' WHERE word = 'obfuscate';
UPDATE spelling_word_bank SET ipa = '/əbˈsikwiəs/' WHERE word = 'obsequious';
UPDATE spelling_word_bank SET ipa = '/əbˈstɹɛpɝəs/' WHERE word = 'obstreperous';
UPDATE spelling_word_bank SET ipa = '/ˌɑkjəˈpeɪʃən/' WHERE word = 'occupation';
UPDATE spelling_word_bank SET ipa = '/ɑkjəˈpeɪʃənəɫ/' WHERE word = 'occupational';
UPDATE spelling_word_bank SET ipa = '/əˈkɝd/' WHERE word = 'occurred';
UPDATE spelling_word_bank SET ipa = '/əˈkɝəns/' WHERE word = 'occurrence';
UPDATE spelling_word_bank SET ipa = '/əˈkɝɪŋ/' WHERE word = 'occurring';
UPDATE spelling_word_bank SET ipa = '/ˌoʊɫiˈædʒənəs/' WHERE word = 'oleaginous';
UPDATE spelling_word_bank SET ipa = '/ˈɑpjəɫəns/' WHERE word = 'opulence';
UPDATE spelling_word_bank SET ipa = '/ˈɑsəˌɫeɪt/' WHERE word = 'oscillate';
UPDATE spelling_word_bank SET ipa = '/ˌɔˈsɪɫəˌskoʊp/' WHERE word = 'oscilloscope';
UPDATE spelling_word_bank SET ipa = '/ˌɑstənˈteɪʃəs/' WHERE word = 'ostentatious';
UPDATE spelling_word_bank SET ipa = '/ˌpænəˈsiə/' WHERE word = 'panacea';
UPDATE spelling_word_bank SET ipa = '/ˈpɛɹəˌɫɛɫ/' WHERE word = 'parallel';
UPDATE spelling_word_bank SET ipa = '/ˈpɛɹəˌɫaɪz/' WHERE word = 'paralyze';
UPDATE spelling_word_bank SET ipa = '/pɝˈɛnθəsɪs/' WHERE word = 'parenthesis';
UPDATE spelling_word_bank SET ipa = '/ˈpɑɹɫəmənt/' WHERE word = 'parliament';
UPDATE spelling_word_bank SET ipa = '/ˌpɑɹsəˈmoʊniəs/' WHERE word = 'parsimonious';
UPDATE spelling_word_bank SET ipa = '/pɑɹˈtɪsəˌpeɪt/' WHERE word = 'participate';
UPDATE spelling_word_bank SET ipa = '/pəkˈjuɫjɝ/, /pɪkˈjuɫjɝ/' WHERE word = 'peculiar';
UPDATE spelling_word_bank SET ipa = '/pɝˈnɪʃəs/' WHERE word = 'pernicious';
UPDATE spelling_word_bank SET ipa = '/ˌpɝpənˈdɪkjəɫɝ/' WHERE word = 'perpendicular';
UPDATE spelling_word_bank SET ipa = '/ˌpɝpɪtˈjuɪti/' WHERE word = 'perpetuity';
UPDATE spelling_word_bank SET ipa = '/pɝˈspɛktɪv/' WHERE word = 'perspective';
UPDATE spelling_word_bank SET ipa = '/pɝspəˈkeɪʃəs/' WHERE word = 'perspicacious';
UPDATE spelling_word_bank SET ipa = '/ˈpɛtʃəɫənt/' WHERE word = 'petulant';
UPDATE spelling_word_bank SET ipa = '/ˌfɑɹməˈsutɪkəɫ/' WHERE word = 'pharmaceutical';
UPDATE spelling_word_bank SET ipa = '/ˈfeɪz/' WHERE word = 'phase';
UPDATE spelling_word_bank SET ipa = '/ˌfɛnɑɫfˈθeɪɫən/, /ˌfinɑɫfˈθeɪɫən/' WHERE word = 'phenolphthalein';
UPDATE spelling_word_bank SET ipa = '/fəˈnɑmənə/' WHERE word = 'phenomena';
UPDATE spelling_word_bank SET ipa = '/fəˈnɑməˌnɑn/' WHERE word = 'phenomenon';
UPDATE spelling_word_bank SET ipa = '/fəˈɫɑsəfi/' WHERE word = 'philosophy';
UPDATE spelling_word_bank SET ipa = '/ˌfoʊtoʊˈkɛməkəɫ/, /ˌfoʊtoʊˈkɛmɪkəɫ/' WHERE word = 'photochemical';
UPDATE spelling_word_bank SET ipa = '/ˌpɑɫəˈneɪʃən/' WHERE word = 'pollination';
UPDATE spelling_word_bank SET ipa = '/pəˈɫuʃən/' WHERE word = 'pollution';
UPDATE spelling_word_bank SET ipa = '/ˌpɑˌɫiˈnoʊmiəɫ/' WHERE word = 'polynomial';
UPDATE spelling_word_bank SET ipa = '/ˈpɑzətɪvɫi/' WHERE word = 'positively';
UPDATE spelling_word_bank SET ipa = '/pɹɪˈsɪpɪˌteɪt/' WHERE word = 'precipitate';
UPDATE spelling_word_bank SET ipa = '/pɹɪˌsɪpɪˈteɪʃən/' WHERE word = 'precipitation';
UPDATE spelling_word_bank SET ipa = '/ˌpɹɛfɝˈɛnʃəɫi/' WHERE word = 'preferentially';
UPDATE spelling_word_bank SET ipa = '/pɹəˈfɝd/, /pɹiˈfɝd/, /pɹɪˈfɝd/' WHERE word = 'preferred';
UPDATE spelling_word_bank SET ipa = '/pɹɪˈfɝɪŋ/' WHERE word = 'preferring';
UPDATE spelling_word_bank SET ipa = '/ˈpɹɪnsəpəɫ/' WHERE word = 'principle';
UPDATE spelling_word_bank SET ipa = '/ˈpɹɑˌsɛs/, /ˈpɹɔˌsɛs/' WHERE word = 'process';
UPDATE spelling_word_bank SET ipa = '/ˈpɹɑsɛsɪŋ/' WHERE word = 'processing';
UPDATE spelling_word_bank SET ipa = '/pɹəˈfɛʃənəɫ/' WHERE word = 'professional';
UPDATE spelling_word_bank SET ipa = '/ˈpɹɔfɫɪˌɡeɪt/' WHERE word = 'profligate';
UPDATE spelling_word_bank SET ipa = '/ˈpɹoʊɫɑɡ/' WHERE word = 'prologue';
UPDATE spelling_word_bank SET ipa = '/pɹəˈpɔɹʃənəɫ/' WHERE word = 'proportional';
UPDATE spelling_word_bank SET ipa = '/pɹəˌpɔɹʃəˈnæɫɪti/' WHERE word = 'proportionality';
UPDATE spelling_word_bank SET ipa = '/pɹəˈpɹaɪətɝ/' WHERE word = 'proprietor';
UPDATE spelling_word_bank SET ipa = '/ˌsaɪkəˈɫɑdʒɪkəɫ/' WHERE word = 'psychological';
UPDATE spelling_word_bank SET ipa = '/ˌsaɪkəˈɫɑdʒɪkɫi/' WHERE word = 'psychologically';
UPDATE spelling_word_bank SET ipa = '/saɪˈkɑɫədʒi/' WHERE word = 'psychology';
UPDATE spelling_word_bank SET ipa = '/pjusəˈɫænəməs/' WHERE word = 'pusillanimous';
UPDATE spelling_word_bank SET ipa = '/ˌkwɛstʃəˈnɛɹ/' WHERE word = 'questionnaire';
UPDATE spelling_word_bank SET ipa = '/ˌkwɪntɪˈsɛnʃəɫ/' WHERE word = 'quintessential';
UPDATE spelling_word_bank SET ipa = '/ˈɹædəkəɫ/, /ˈɹædɪkəɫ/' WHERE word = 'radical';
UPDATE spelling_word_bank SET ipa = '/ɹɪˈkæɫsɪtɹənt/' WHERE word = 'recalcitrant';
UPDATE spelling_word_bank SET ipa = '/ɹɪˈsɪpɹəkəɫ/' WHERE word = 'reciprocal';
UPDATE spelling_word_bank SET ipa = '/ɹiˈkɑnəsəns/' WHERE word = 'reconnaissance';
UPDATE spelling_word_bank SET ipa = '/ˌɹikənˈstɹəkʃən/' WHERE word = 'reconstruction';
UPDATE spelling_word_bank SET ipa = '/ˈɹɛktæŋɡəɫ/' WHERE word = 'rectangle';
UPDATE spelling_word_bank SET ipa = '/ɹɛkˈtæŋɡjəɫɝ/' WHERE word = 'rectangular';
UPDATE spelling_word_bank SET ipa = '/ˌɹidɪˈvɛɫəpmənt/' WHERE word = 'redevelopment';
UPDATE spelling_word_bank SET ipa = '/ɹəˈfɝd/, /ɹɪˈfɝd/' WHERE word = 'referred';
UPDATE spelling_word_bank SET ipa = '/ɹɪˈfɝɪŋ/' WHERE word = 'referring';
UPDATE spelling_word_bank SET ipa = '/ˌɹiɫækˈseɪʃən/' WHERE word = 'relaxation';
UPDATE spelling_word_bank SET ipa = '/ɹiˌɫaɪəˈbɪɫəti/' WHERE word = 'reliability';
UPDATE spelling_word_bank SET ipa = '/ˌɹipɹəˈdəktɪv/' WHERE word = 'reproductive';
UPDATE spelling_word_bank SET ipa = '/ˌɹɛspɝˈeɪʃən/' WHERE word = 'respiration';
UPDATE spelling_word_bank SET ipa = '/ˈɹɛspɝəˌtɔɹi/' WHERE word = 'respiratory';
UPDATE spelling_word_bank SET ipa = '/ɹɪˈspɑnsɪvnəs/' WHERE word = 'responsiveness';
UPDATE spelling_word_bank SET ipa = '/ɹiˈviɫ/, /ɹɪˈviɫ/' WHERE word = 'reveal';
UPDATE spelling_word_bank SET ipa = '/ˌɹɛvəˈɫuʃəˌnɛɹiz/' WHERE word = 'revolutionaries';
UPDATE spelling_word_bank SET ipa = '/ˌɹɛvəˈɫuʃəˌnɛɹi/' WHERE word = 'revolutionary';
UPDATE spelling_word_bank SET ipa = '/ˌɹoʊdəˈdɛndɹən/' WHERE word = 'rhododendron';
UPDATE spelling_word_bank SET ipa = '/ˈɹaɪm/' WHERE word = 'rhyme';
UPDATE spelling_word_bank SET ipa = '/ˈɹɪðəm/' WHERE word = 'rhythm';
UPDATE spelling_word_bank SET ipa = '/ˈɹʊɹəɫ/' WHERE word = 'rural';
UPDATE spelling_word_bank SET ipa = '/ˈskɹutəˌnaɪz/' WHERE word = 'scrutinize';
UPDATE spelling_word_bank SET ipa = '/ˌsɛdəˈmɛntɝi/' WHERE word = 'sedimentary';
UPDATE spelling_word_bank SET ipa = '/ˌsɛnsɪˈbɪɫɪti/' WHERE word = 'sensibility';
UPDATE spelling_word_bank SET ipa = '/ˌsɛɹənˈdɪpɪti/' WHERE word = 'serendipity';
UPDATE spelling_word_bank SET ipa = '/səɡˈnɪfɪkənt/, /sɪɡˈnɪfɪkənt/' WHERE word = 'significant';
UPDATE spelling_word_bank SET ipa = '/sɪɡˈnɪfɪkəntɫi/' WHERE word = 'significantly';
UPDATE spelling_word_bank SET ipa = '/ˌsaɪməɫˈteɪniəs/' WHERE word = 'simultaneous';
UPDATE spelling_word_bank SET ipa = '/səˈfɪstəˌkeɪtɪd/, /səˈfɪstɪˌkeɪtəd/' WHERE word = 'sophisticated';
UPDATE spelling_word_bank SET ipa = '/ˈspiʃiz/' WHERE word = 'species';
UPDATE spelling_word_bank SET ipa = '/ˈsfɪɹ/' WHERE word = 'sphere';
UPDATE spelling_word_bank SET ipa = '/ˈsfɛɹɪkəɫ/' WHERE word = 'spherical';
UPDATE spelling_word_bank SET ipa = '/ˈsteɪbəɫ/' WHERE word = 'stable';
UPDATE spelling_word_bank SET ipa = '/ˈsteɪʃəˌnɛɹi/' WHERE word = 'stationary';
UPDATE spelling_word_bank SET ipa = '/stəˈtɪstɪkəɫ/' WHERE word = 'statistical';
UPDATE spelling_word_bank SET ipa = '/ˈstɛdˌfæst/' WHERE word = 'steadfast';
UPDATE spelling_word_bank SET ipa = '/ˈstɪmjəˌɫeɪt/' WHERE word = 'stimulate';
UPDATE spelling_word_bank SET ipa = '/ˈstɹɛs/' WHERE word = 'stress';
UPDATE spelling_word_bank SET ipa = '/səˈbɔɹdəˌneɪt/, /səˈbɔɹdənət/' WHERE word = 'subordinate';
UPDATE spelling_word_bank SET ipa = '/ˌsəbstɪˈtuʃən/' WHERE word = 'substitution';
UPDATE spelling_word_bank SET ipa = '/səbˈtɹækʃən/' WHERE word = 'subtraction';
UPDATE spelling_word_bank SET ipa = '/səkˈsɛsɝ/' WHERE word = 'successor';
UPDATE spelling_word_bank SET ipa = '/ˈsəmɝˌaɪzɪz/' WHERE word = 'summarizes';
UPDATE spelling_word_bank SET ipa = '/ˈsəmɝˌaɪzɪŋ/' WHERE word = 'summarizing';
UPDATE spelling_word_bank SET ipa = '/ˈsəmɝi/' WHERE word = 'summary';
UPDATE spelling_word_bank SET ipa = '/ˌsupɪɹiˈɔɹɪti/' WHERE word = 'superiority';
UPDATE spelling_word_bank SET ipa = '/ˈsəpɫəmənt/, /ˌsəpɫəˈmɛnt/' WHERE word = 'supplement';
UPDATE spelling_word_bank SET ipa = '/ˌsəpɫəˈmɛnɝi/, /ˌsəpɫəˈmɛntɝi/, /ˌsəpɫəˈmɛntɹi/, /ˌsəpɫəˈmɛntʃɹi/' WHERE word = 'supplementary';
UPDATE spelling_word_bank SET ipa = '/ˈsɪɫəbəɫ/' WHERE word = 'syllable';
UPDATE spelling_word_bank SET ipa = '/səˈmɛtɹɪkəɫ/' WHERE word = 'symmetrical';
UPDATE spelling_word_bank SET ipa = '/tænˈdʒɛnʃəɫ/' WHERE word = 'tangential';
UPDATE spelling_word_bank SET ipa = '/ˈtɔt/' WHERE word = 'taught';
UPDATE spelling_word_bank SET ipa = '/ˌtɛknəˈɫɑdʒɪkəɫ/' WHERE word = 'technological';
UPDATE spelling_word_bank SET ipa = '/ˌtɛɫəkəmˌjunɪˈkeɪʃən/' WHERE word = 'telecommunication';
UPDATE spelling_word_bank SET ipa = '/ˈtɛɫəˌskoʊp/' WHERE word = 'telescope';
UPDATE spelling_word_bank SET ipa = '/ˌtɛɹɪˈtɔɹiəɫ/' WHERE word = 'territorial';
UPDATE spelling_word_bank SET ipa = '/ˈtɛɹəˌtɔɹiz/' WHERE word = 'territories';
UPDATE spelling_word_bank SET ipa = '/ˈtɛɹɪˌtɔɹi/' WHERE word = 'territory';
UPDATE spelling_word_bank SET ipa = '/ˈtɛkst/' WHERE word = 'text';
UPDATE spelling_word_bank SET ipa = '/ˌθiɝˈɛtɪkəɫ/' WHERE word = 'theoretical';
UPDATE spelling_word_bank SET ipa = '/ˈθɝməɫ/' WHERE word = 'thermal';
UPDATE spelling_word_bank SET ipa = '/θɝˈmɑmətɝ/' WHERE word = 'thermometer';
UPDATE spelling_word_bank SET ipa = '/ˈθɝoʊ/, /ˈθɔɹoʊ/' WHERE word = 'thorough';
UPDATE spelling_word_bank SET ipa = '/ˈθɝoʊˌfɛɹ/' WHERE word = 'thoroughfare';
UPDATE spelling_word_bank SET ipa = '/ˈθɔt/' WHERE word = 'thought';
UPDATE spelling_word_bank SET ipa = '/ˈtəf/' WHERE word = 'tough';
UPDATE spelling_word_bank SET ipa = '/tɹəˈdɪʃənəɫ/' WHERE word = 'traditional';
UPDATE spelling_word_bank SET ipa = '/tɹəˈdɪʃənəɫi/, /tɹəˈdɪʃnəɫi/' WHERE word = 'traditionally';
UPDATE spelling_word_bank SET ipa = '/ˈtɹænsfɝd/, /tɹænsˈfɝd/' WHERE word = 'transferred';
UPDATE spelling_word_bank SET ipa = '/tɹænsˈfɝɪŋ/' WHERE word = 'transferring';
UPDATE spelling_word_bank SET ipa = '/ˌtɹænsfɝˈmeɪʃən/' WHERE word = 'transformation';
UPDATE spelling_word_bank SET ipa = '/tɹænˈzɪʃən/' WHERE word = 'transition';
UPDATE spelling_word_bank SET ipa = '/tɹænsˈmɪʃən/, /tɹænzˈmɪʃən/' WHERE word = 'transmission';
UPDATE spelling_word_bank SET ipa = '/ˈtɹænspɔɹt/, /tɹænˈspɔɹt/' WHERE word = 'transport';
UPDATE spelling_word_bank SET ipa = '/ˌtɹænspɝˈteɪʃən/' WHERE word = 'transportation';
UPDATE spelling_word_bank SET ipa = '/ˈtɹɑpɪkəɫ/' WHERE word = 'tropical';
UPDATE spelling_word_bank SET ipa = '/ˈtɝbjəɫənt/' WHERE word = 'turbulent';
UPDATE spelling_word_bank SET ipa = '/ənˈkɑnʃənəbəɫ/' WHERE word = 'unconscionable';
UPDATE spelling_word_bank SET ipa = '/ˌənˈkɑnʃəs/' WHERE word = 'unconscious';
UPDATE spelling_word_bank SET ipa = '/ˌənˌkɑnstəˈtuʃənəɫ/' WHERE word = 'unconstitutional';
UPDATE spelling_word_bank SET ipa = '/ˌəniˈkwɪvəkəɫi/, /ˌəniˈkwɪvəkɫi/' WHERE word = 'unequivocally';
UPDATE spelling_word_bank SET ipa = '/ˌjunɪˈsɛɫjəɫɝ/' WHERE word = 'unicellular';
UPDATE spelling_word_bank SET ipa = '/ˌjunəvɝˈsæɫəti/' WHERE word = 'universality';
UPDATE spelling_word_bank SET ipa = '/ənˈnɛsəˌsɛɹi/' WHERE word = 'unnecessary';
UPDATE spelling_word_bank SET ipa = '/vəˈɫɑsəti/' WHERE word = 'velocity';
UPDATE spelling_word_bank SET ipa = '/ˈvɝbəɫ/' WHERE word = 'verbal';
UPDATE spelling_word_bank SET ipa = '/ˌvɛɹəsəˈmɪɫəˌtud/' WHERE word = 'verisimilitude';
UPDATE spelling_word_bank SET ipa = '/ˈvɝtɪkəɫ/' WHERE word = 'vertical';
UPDATE spelling_word_bank SET ipa = '/ˈvɪʒəwəɫ/' WHERE word = 'visual';
UPDATE spelling_word_bank SET ipa = '/ˌvaɪˈtupɝətɪv/, /vəˈtupɝətɪv/' WHERE word = 'vituperative';
UPDATE spelling_word_bank SET ipa = '/voʊˈkæbjəˌɫɛɹi/' WHERE word = 'vocabulary';
UPDATE spelling_word_bank SET ipa = '/ˈvɑɫjəbəɫ/' WHERE word = 'voluble';
UPDATE spelling_word_bank SET ipa = '/ˈvɑɫəntɛɹi/' WHERE word = 'voluntary';
UPDATE spelling_word_bank SET ipa = '/vɔˈɹeɪʃəs/' WHERE word = 'voracious';
UPDATE spelling_word_bank SET ipa = '/ˈweɪwɝd/' WHERE word = 'wayward';
UPDATE spelling_word_bank SET ipa = '/ˈweɪ/' WHERE word = 'weigh';
UPDATE spelling_word_bank SET ipa = '/ˈweɪt/' WHERE word = 'weight';
UPDATE spelling_word_bank SET ipa = '/ˈwɪɫɪŋnəs/' WHERE word = 'willingness';
UPDATE spelling_word_bank SET ipa = '/ˈwɪstfəɫ/' WHERE word = 'wistful';
UPDATE spelling_word_bank SET ipa = '/ˈju/' WHERE word = 'yew';
UPDATE spelling_word_bank SET ipa = '/ˈzɛɫəs/' WHERE word = 'zealous';
UPDATE spelling_word_bank SET ipa = '/ˈzinəθ/, /ˈzinɪθ/' WHERE word = 'zenith';
